[package]
name = "hex-edit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
structopt = "0.3.26"
console = "0.15.0"
crossterm = "0.24.0"